### ISSUE TITLE
yarn build fails

### ISSUE THREAD

**Issue by soumyaDghosh** [vixalien/muzika#6]
Hii, I was trying to snap your app. But while building, your code fails in the yarn building part.

```
:: /usr/local/bin/yarn --cwd /build/muzika/parts/muzika/src run build --out /build/muzika/parts/muzika/build/src --cwd /build/muzika/parts/muzika/build ../src/src/main.ts
:: yarn run v1.22.19
:: $ node lib/build.js --out /build/muzika/parts/muzika/build/src --cwd /build/muzika/parts/muzika/build ../src/src/main.ts
:: file:///build/muzika/parts/muzika/src/lib/build.js:21
:: await build({
:: ^^^^^
::
:: SyntaxError: Unexpected reserved word
::     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
::     at async link (internal/modules/esm/module_job.js:42:21)
:: error Command failed with exit code 1.
:: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
:: ninja: build stopped: subcommand failed.
:: error: Failed to run the build script for part 'muzika'.
```

This is the error log. Can you help me fixing this?

**Comment by DaPigGuy** [comment]
What Node.js version do you have installed?

**Comment by soumyaDghosh** [comment]
This is from the jammy repo, version `12.22.9`

**Comment by DaPigGuy** [comment]
You'll need `14.8` or later

**Comment by soumyaDghosh** [comment]
Thanks, I will use ppa for nodejs

**Comment by vixalien** [comment]
you can also use nvm, which is what I would recommend.

**Comment by soumyaDghosh** [comment]
No I installed nodejs from the official repos, no problem, it built successfully. In the store soon.

**Comment by soumyaDghosh** [comment]
Okay so, after adding all the deps and necessary packages, this app builds. But when I run this app, I get

```
Gjs-Console-Message: 16:53:22.495: caching soup requests at /home/soumyaxubuntu/snap/muzika/common/.cache/com.vixalien.muzika/soup-cache
Gjs-Console-Message: 16:53:22.496: storing data at /home/soumyaxubuntu/snap/muzika/x4/.local/share/com.vixalien.muzika/store.json
Gjs-Console-Message: 16:53:22.496: caching data at /home/soumyaxubuntu/snap/muzika/common/.cache/com.vixalien.muzika/cache

(com.vixalien.muzika:7782): Gjs-CRITICAL **: 16:53:22.505: JS ERROR: TypeError: method Gio.ActionMap.add_action_entries: At least 2 arguments required, but only 1 passed
init_actions@resource:///com/vixalien/muzika/js/main.js:19230:10
_Application@resource:///com/vixalien/muzika/js/main.js:19198:10
main@resource:///com/vixalien/muzika/js/main.js:19263:15
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@file:///snap/muzika/x4/usr/bin/com.vixalien.muzika:22:40
@file:///snap/muzika/x4/usr/bin/com.vixalien.muzika:28:6
```

I don't think, this issue is related to any library, but this seems to be issue in the code itself.

**Comment by DaPigGuy** [comment]
You need gjs 1.73.1 or later. This builds fine under Flatpak with the GNOME 44 runtime

**Comment by soumyaDghosh** [comment]
I will try then, the gnome-sdk has version 1.72.3, I will update it and then check it out. Keeping this PR open for now

**Comment by soumyaDghosh** [comment]
> which GNOME Sdk are you using?
> 
> Try changing the following line
> 
> https://github.com/vixalien/muzika/blob/af0ee9e99529e2a3850c9cd721d720755e1a9217/src/application.ts#L29
> 
> to
> 
> ```js
>     ], -1);
> ```

I am using the gnome-sdk of snap, [gnome-42-2204-sdk](https://github.com/ubuntu/gnome-sdk), I think, I can wait, but just adding a -1 can make it work in 1.72.3?

**Comment by soumyaDghosh** [comment]
No help, this is the new error log

```
Gjs-Console-Message: 00:03:57.031: caching soup requests at /home/soumyaxubuntu/snap/muzika/common/.cache/com.vixalien.muzika/soup-cache
Gjs-Console-Message: 00:03:57.032: storing data at /home/soumyaxubuntu/snap/muzika/7/.local/share/com.vixalien.muzika/store.json
Gjs-Console-Message: 00:03:57.032: caching data at /home/soumyaxubuntu/snap/muzika/common/.cache/com.vixalien.muzika/cache

(com.vixalien.muzika:28867): Gjs-CRITICAL **: 00:03:57.043: JS ERROR: TypeError: Object 0x2d1e14d00158 is not a subclass of GObject_Boxed, it's a Object
init_actions@resource:///com/vixalien/muzika/js/main.js:20122:10
_Application@resource:///com/vixalien/muzika/js/main.js:20090:10
main@resource:///com/vixalien/muzika/js/main.js:20155:15
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@file:///snap/muzika/7/usr/bin/com.vixalien.muzika:22:40
@file:///snap/muzika/7/usr/bin/com.vixalien.muzika:28:6

```

**Comment by vixalien** [comment]
oh I don't think this is gonna work with snap at all, given the severely outdated SDK.

also note that in #9 which will get merged soon, we will be using the latest builds of libadwaita which requires compiling it from source until GNOME 45 gets released (September.)

Flatpak makes it really easy but I don't really know about Snap (see `build-aux/flatpak/com.vixalien.muzika.json`)

**Comment by soumyaDghosh** [comment]
Gnome-SDK for snap is also built from the source not the repo, I have those PRs ready, but they're currently in the pipeline.

**Comment by vixalien** [comment]
ah okay. does it use the latest sources?

this is because you'll probably use a custom SDK with changes that are not yet tagged: libadwaita 1.4 (building from main)

**Comment by soumyaDghosh** [comment]
Well, not that latest. It uses the latest stable one. Libadwaita1.4 isn't stable yet. It has libadwaita1.3. The problem here is libgjs wasn't updated for last 5 months. That I guess caused this.

**Comment by vixalien** [comment]
ah okay.

I was saying that for the latest version of this app, you'll need to build libadwaita (and GTK) from source since it requires libadwaita 1.4

**Comment by soumyaDghosh** [comment]
Building gtk4 from source seems very tough. I tried for loupe and snapshot but failed. Yet, I'll try again.

**Comment by vixalien** [comment]
ah okay. good luck!

**Comment by soumyaDghosh** [comment]
Don't worry your app will be available to Ubuntu users. @DaPigGuy knows how much dedicated I'm for snaps.

**Comment by vixalien** [comment]
haha you seem so committed!

**Comment by soumyaDghosh** [comment]
Hii @vixalien thanks for all the patience, as you can see, I have [updated](https://github.com/ubuntu/gnome-sdk/pull/151) `gjs` in gnome-sdk, and the old version worked fine. But, the new one from the latest commit is giving me some hickups, can you explain me what are used for it?

I am using `blueprint-compiler` `v0.8.1` and the first error I am facing is

```
:: /usr/bin/blueprint-compiler batch-compile data/ui/ui ../src/data/ui ../src/data/ui/components/album/item.blp ../src/data/ui/components/carousel/card.blp ../src/data/ui/components/carousel/carousel.blp ../src/data/ui/components/carousel/flatsong.blp ../src/data/ui/components/dynamic-image.blp ../src/data/ui/components/library/history.blp ../src/data/ui/components/library/mixedcard.blp ../src/data/ui/components/library/songs.blp ../src/data/ui/components/library/view.blp ../src/data/ui/components/loading.blp ../src/data/ui/components/nav/page.blp ../src/data/ui/components/navbar/button.blp ../src/data/ui/components/navbar/index.blp ../src/data/ui/components/navbar/section.blp ../src/data/ui/components/navbar/title.blp ../src/data/ui/components/paginator.blp ../src/data/ui/components/player/full.blp ../src/data/ui/components/player/lyrics.blp ../src/data/ui/components/player/mini.blp ../src/data/ui/components/player/queue.blp ../src/data/ui/components/player/queueitem.blp ../src/data/ui/components/player/related.blp ../src/data/ui/components/playlist-image.blp ../src/data/ui/components/playlist/item.blp ../src/data/ui/components/playlist/largeheader.blp ../src/data/ui/components/playlist/listitem.blp ../src/data/ui/components/playlist/miniheader.blp ../src/data/ui/components/search/inlinecard.blp ../src/data/ui/components/search/section.blp ../src/data/ui/components/search/songcard.blp ../src/data/ui/components/search/topresult.blp ../src/data/ui/components/search/topresultsection.blp ../src/data/ui/gtk/help-overlay.blp ../src/data/ui/pages/album.blp ../src/data/ui/pages/artist.blp ../src/data/ui/pages/authentication-error.blp ../src/data/ui/pages/error.blp ../src/data/ui/pages/home.blp ../src/data/ui/pages/login.blp ../src/data/ui/pages/playlist.blp ../src/data/ui/pages/search.blp ../src/data/ui/window.blp
:: error: Could not determine what kind of syntax is meant here
:: at ../src/data/ui/components/album/item.blp line 3 column 10:
::    3 |template $AlbumItem : ListBoxRow {
::      |         ^
::

```

Is this issue related to `libadwaita`? As it seems to be updated.

**Comment by DaPigGuy** [comment]
Ubuntu 22.04 is on a blueprint-compiler version tagged from 2023-03-02, while the `$` syntax was introduced in `v0.8.0` released May of this year.

**Comment by soumyaDghosh** [comment]
> while the `$` syntax was introduced in `v0.8.0` released May of this year. No supported version of Ubuntu has an up to date version.

I am not using `blueprint-compiler` from repos, instead building it from source-tag `0.8.1` as I have said before. And this is the repo, I am using to test the builds, I might have missed some lines from the error. 

https://launchpad.net/~soumyadghosh/+snap/muzika

Look into one of the latest build-errors

**Comment by soumyaDghosh** [comment]
Thanks for pointing it out. Indeed, I forgot to push the commit that built `blueprint-compiler` from source. Thanks and sorry about that. Still, this link will help you track the snap,

https://launchpad.net/~soumyadghosh/+snap/muzika
